[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 2EKa6Oo5gZwuURJgIsFHUX1nouvuPc/JL9yRa1BGGlo=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# NL-FREE#231
PublicKey = oT8RknmSYsLqvQv68xcKiVY4PYpSiyM7YSL7efAFKXM=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 190.2.149.217:51820

PersistentKeepalive = 25