- switch:
    name: "VPN Dom Global"
    unique_id: vpn_dom_global_v2
    command_on: "ssh -n -p 3022 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@192.168.1.1 '/root/toggle-vpn on'"
    command_off: "ssh -n -p 3022 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@192.168.1.1 '/root/toggle-vpn off'"
    command_state: "ssh -n -p 3022 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@192.168.1.1 'ip rule show | grep -q \"50:\"'"
    scan_interval: 2

- switch:
    name: "VPN Dom Select"
    unique_id: vpn_dom_select_v2
    command_on: "ssh -n -p 3022 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@192.168.1.1 '/root/toggle-vpn selective_on'"
    command_off: "ssh -n -p 3022 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@192.168.1.1 '/root/toggle-vpn off'"
    command_state: "ssh -n -p 3022 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@192.168.1.1 'ip rule show | grep -q \"45:\"'"
    scan_interval: 2

- switch:
    name: "VPN Dostawca P/W"
    unique_id: vpn_dostawca_p_w_v2
    command_on: "ssh -n -p 3022 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@192.168.1.1 '/root/switch-provider.sh PROTON'"
    command_off: "ssh -n -p 3022 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@192.168.1.1 '/root/switch-provider.sh WARP'"
    command_state: "ssh -n -p 3022 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@192.168.1.1 'grep -q \"PROTON\" /root/.vpn_provider'"
    scan_interval: 2

- sensor:
    name: "VPN Status Serwer"
    unique_id: vpn_status_serwer_v2
    command: "ssh -n -p 3022 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@192.168.1.1 '/root/toggle-vpn status'"
    scan_interval: 1800
    value_template: "{{ value }}"