# Startuj strumienie od razu (szybszy “pierwszy kadr”)
preload:
  kamera: "video"
  kamera2: "video"

streams:
  kamera:
    - 'echo:curl -fsSL --connect-timeout 2 --max-time 5 http://supervisor/core/api/camera_stream_source/camera.kamera -H "Authorization: Bearer ${SUPERVISOR_TOKEN}"'
  kamera2:
    - 'echo:curl -fsSL --connect-timeout 2 --max-time 5 http://supervisor/core/api/camera_stream_source/camera.kamera2 -H "Authorization: Bearer ${SUPERVISOR_TOKEN}"'