lgtv_picture_mode:
  alias: LG TV Picture Mode
  description: ''
  mode: single
  sequence:
  - action: webostv.command
    data:
      entity_id: media_player.lg_tv
      command: system.notifications/createAlert
      payload:
        message: 'Ustawiono tryb obrazu: {{ picture_mode }}'
        modal: false
        buttons:
        - label: ok
          focus: true
          buttonType: ok
          onClick: luna://com.webos.settingsservice/setSystemSettings
          params:
            category: picture
            settings:
              pictureMode: '{{ picture_mode }}'
        type: confirm
        isSysReq: true
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ picture_mode | lower == ''filmmaker'' }}'
      sequence:
      - delay:
          milliseconds: 6
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 200
  - action: webostv.button
    data:
      entity_id: media_player.lg_tv
      button: ENTER
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ picture_mode | lower == ''filmmaker'' }}'
      sequence:
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 200
      - action: webostv.command
        data:
          entity_id: media_player.lg_tv
          command: system.notifications/createAlert
          payload:
            message: Eye Comfort OFF
            modal: false
            buttons:
            - label: ok
              focus: true
              buttonType: ok
              onClick: luna://com.webos.settingsservice/setSystemSettings
              params:
                category: picture
                settings:
                  eyeComfortMode: 'off'
            type: confirm
            isSysReq: true
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 200
      - action: webostv.button
        data:
          entity_id: media_player.lg_tv
          button: ENTER
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ picture_mode | lower in [''expert1'',''expert2''] }}

          '
      sequence:
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 200
      - action: webostv.command
        data:
          entity_id: media_player.lg_tv
          command: system.notifications/createAlert
          payload:
            message: Eye Comfort ON
            modal: false
            buttons:
            - label: ok
              focus: true
              buttonType: ok
              onClick: luna://com.webos.settingsservice/setSystemSettings
              params:
                category: picture
                settings:
                  eyeComfortMode: 'on'
            type: confirm
            isSysReq: true
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 200
      - action: webostv.button
        data:
          entity_id: media_player.lg_tv
          button: ENTER
lgtv_script:
  alias: LGTV_Script
  description: ''
  sequence:
  - target:
      entity_id: button.lgtv
    action: button.press
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
    enabled: true
  - data:
      entity_id: media_player.lg_tv
      command: system.launcher/launch
      payload:
        id: com.webos.app.home
    action: webostv.command
    enabled: true
fear_pc_script:
  alias: FEAR-PC_Script
  sequence:
  - action: button.press
    metadata: {}
    data: {}
    target:
      device_id: 82d438cb58cfac2ce0769bed5bbaa7bf
  description: ''
lgtv_script_off:
  alias: LGTV_Script_OFF
  sequence:
  - action: input_button.press
    metadata: {}
    data: {}
    target:
      entity_id:
      - input_button.lgtv_manual2
  description: ''
lgtv_script_off_now:
  sequence:
  - action: input_button.press
    metadata: {}
    data: {}
    target:
      entity_id: input_button.lgtv_manual
  alias: LGTV_Script_OFF_NOW
  description: ''
confirmable_notification:
  alias: Confirmable Notification
  use_blueprint:
    path: homeassistant/confirmable_notification.yaml
    input:
      confirm_action:
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          device_id: d36e7b1056abfdb139090057df440135
      - type: turn_on
        device_id: 1ff9b911c0d913696269646267fc72f8
        entity_id: 1b6dbf68e8f5a3110059c22c291d8229
        domain: switch
      - action: button.press
        metadata: {}
        data: {}
        target:
          device_id: 82d438cb58cfac2ce0769bed5bbaa7bf
      notify_device: c0f9f62075fdbe1fb9cb0a0599ea9a12
      title: ' '
      message: Arrive - Włącz Przedpokój 1 i Pokój
      confirm_text: Potwierdź
      dismiss_text: Odrzuć
  description: ''
lg_tv_wylacz_ekran:
  alias: LG TV OFF Screen
  description: ''
  mode: single
  sequence:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 250
  - data:
      entity_id: media_player.lg_tv
      command: system.notifications/createToast
      payload:
        message: Ekran zaraz wyłączy się.
    action: webostv.command
    enabled: false
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 250
    enabled: false
  - data:
      entity_id: media_player.lg_tv
      command: com.webos.service.tvpower/power/turnOffScreen
    action: webostv.command
wyciszenieonn:
  alias: Mute OnnTvBox
  sequence:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ is_state_attr(''media_player.android_tv_192_168_1_22'',
          ''is_volume_muted'', true) }}'
      sequence:
      - data:
          is_volume_muted: false
        action: media_player.volume_mute
        target:
          device_id: 7226f200b803090f770aceb04010e689
    default:
    - data:
        is_volume_muted: true
      action: media_player.volume_mute
      target:
        device_id: 7226f200b803090f770aceb04010e689
  description: ''
clear_log:
  alias: Clear LOG
  sequence:
  - action: shell_command.clear_log
    data: {}
  mode: single
  icon: mdi:eraser-variant
  description: ''
lgtv_script_live:
  sequence:
  - target:
      entity_id: button.lgtv
    action: button.press
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
    enabled: true
  - data:
      entity_id: media_player.lg_tv
      command: system.launcher/launch
      payload:
        id: com.webos.app.livetv
    action: webostv.command
    enabled: true
  alias: LGTV ON LIVE
  description: ''
lgtv_yt_watchlater_play:
  alias: LGTV ON Twitch
  mode: restart
  sequence:
  - target:
      entity_id: button.lgtv
    action: button.press
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - data:
      entity_id: media_player.lg_tv
      command: system.launcher/launch
      payload:
        id: com.webos.app.home
    action: webostv.command
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - data:
      entity_id: media_player.lg_tv
      button: BACK
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 800
  - data:
      entity_id: media_player.lg_tv
      button: UP
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 800
  - data:
      entity_id: media_player.lg_tv
      button: UP
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 800
  - data:
      entity_id: media_player.lg_tv
      button: ENTER
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 800
  - data:
      entity_id: media_player.lg_tv
      command: system.launcher/launch
      payload:
        id: tv.twitch.tv.starshot.lg
    action: webostv.command
  - delay:
      hours: 0
      minutes: 0
      seconds: 8
      milliseconds: 0
  - data:
      entity_id: media_player.lg_tv
      button: UP
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 400
  - data:
      entity_id: media_player.lg_tv
      button: RIGHT
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 400
  - data:
      entity_id: media_player.lg_tv
      button: ENTER
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - data:
      entity_id: media_player.lg_tv
      button: ENTER
    action: webostv.button
  description: ''
lgtv_on_yt:
  sequence:
  - target:
      entity_id: button.lgtv
    action: button.press
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - data:
      entity_id: media_player.lg_tv
      command: system.launcher/launch
      payload:
        id: com.webos.app.home
    action: webostv.command
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - data:
      entity_id: media_player.lg_tv
      button: BACK
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 800
  - data:
      entity_id: media_player.lg_tv
      button: UP
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 800
  - data:
      entity_id: media_player.lg_tv
      button: UP
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 800
  - data:
      entity_id: media_player.lg_tv
      button: ENTER
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 800
  - data:
      entity_id: media_player.lg_tv
      command: system.launcher/launch
      payload:
        id: youtube.leanback.v4
    action: webostv.command
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - data:
      entity_id: media_player.lg_tv
      button: ENTER
    action: webostv.button
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
    enabled: true
  - data:
      entity_id: media_player.lg_tv
      button: LEFT
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 300
  - data:
      entity_id: media_player.lg_tv
      button: DOWN
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 300
  - data:
      entity_id: media_player.lg_tv
      button: DOWN
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 300
  - data:
      entity_id: media_player.lg_tv
      button: DOWN
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 300
  - data:
      entity_id: media_player.lg_tv
      button: DOWN
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 300
  - data:
      entity_id: media_player.lg_tv
      button: DOWN
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 300
  - data:
      entity_id: media_player.lg_tv
      button: RIGHT
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 300
  - data:
      entity_id: media_player.lg_tv
      button: RIGHT
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 300
  - data:
      entity_id: media_player.lg_tv
      button: ENTER
    action: webostv.button
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 300
  - data:
      entity_id: media_player.lg_tv
      button: ENTER
    action: webostv.button
  alias: LGTV ON YT
  mode: restart
  description: ''
